### ISSUE TITLE
Getting Cannot read property 'style' of null for those markers which are within a cluster

### ISSUE THREAD

**Issue by dhrubo001** [hosuaby/Leaflet.SmoothMarkerBouncing#1]
![errr](https://cloud.githubusercontent.com/assets/7116995/15575817/6e163eec-2372-11e6-8735-38950f7777b9.png)
Getting Cannot read property 'style' of null for those markers which are within a cluster

function markerFunction(id){
	
	 for (var i in m){
			
            var markerID = m[i].options.title;
			if (markerID == id){
				
				m[i].openPopup();
				
				if(m[i].isBouncing())
				{
					m[i].stopBouncing();
					m[i].closePopup();
				}
				else{
					markers.zoomToShowLayer(m[i], function(){
					m[i].setBouncingOptions({
					bounceHeight : 20,    // height of the bouncing
					bounceSpeed  : 40,    // bouncing speed coefficient
					exclusive    : true,  // if this marker bouncing all others must stop
				   }).bounce();
				});
				}
				
			}
       }
}

And the marker is also vanishes when i zoom into the cluster, and again comes back when i zoom out

What i am doing wrong, help needed

PLEASE CHECK THE ATTACHMENT

**Comment by hosuaby** [comment]
Hello. Currently plugin doesn't work together with cluster plugin. Support for clusters can be added in future versions. You can contribute by adding this feature.

**Comment by dhrubo001** [comment]
Ang remedies wat should i do to overcome this situation??

**Comment by hosuaby** [comment]
For the moment the only solution is not use those two plugins together.

**Comment by dhrubo001** [comment]
ok

**Comment by mat81** [comment]
Hello, sorry my english is not so good, I'm french :)
Your plugin is really great !!
Marker disappear when coming from a cluster, because of opacity = 0 in css
I just add  delete styles['opacity'] for test in onAdd function line 950
It seems all right

**Comment by dhrubo001** [comment]
Can you plz show little bit about our code

**Comment by hosuaby** [comment]
Yes @mat81 you are very close. @dhrubo001  I am fixing issue. Will made a new release very soon

**Comment by hosuaby** [comment]
New release 1.1.3 fixes this issue with Leaflet.MarkerCluster.

**Comment by mrethical** [comment]
This seems to be an issue again with the latest version (2.0.0)

**Comment by hosuaby** [comment]
Hello @mrethical . Version 2.0.0 was tested with `Leaflet.markercluster`. Can you pease provide more details. Browser, versions, code snippet, please.

**Comment by mrethical** [comment]
This is the console log screenshot from the latest version of chrome (v86)
![Capture](https://user-images.githubusercontent.com/54579632/96673040-29ab9700-1398-11eb-89f2-0e59bd5ac2c1.PNG)

Here's the screenshot on the code block responsible on bouncing a marker (btw I'm using typescript):
![Capture](https://user-images.githubusercontent.com/54579632/96673481-32e93380-1399-11eb-8c41-79ab39431454.PNG)

Marker bouncing works, but as soon as I zoom out and the markers are clustered, I get the error.

**Comment by hosuaby** [comment]
@mrethical I confirm this bug. I will try to fix it.

**Comment by hosuaby** [comment]
@mrethical fixed in v2.0.1

**Comment by mrethical** [comment]
Works! Thanks for the fix.
