### ISSUE TITLE
TypeError: (intermediate value).bounce is not a function

### ISSUE THREAD

**Issue by andesim** [hosuaby/Leaflet.SmoothMarkerBouncing#11]
I receive this error:
Uncaught (in promise) TypeError: (intermediate value).bounce is not a function

            var incIcon = new L.icon({
               iconUrl: '/images/icons/incident.png',
               iconSize: [35, 95],
            });
            var marker = new L.marker([e.latlng.lat, e.latlng.lng], {
                icon: incIcon,
                zIndexOffset: 1000
            }).bounce();

**Comment by hosuaby** [comment]
1) Make sure you are imported both Leaflet and import 'leaflet';
import 'leaflet.smooth_marker_bouncing/leaflet.smoothmarkerbouncing.js' in current file or globally

```javascript
import 'leaflet';
import 'leaflet.smooth_marker_bouncing/leaflet.smoothmarkerbouncing.js';
```

2) You forgot `.addTo(map) ` before `.bounce()`
