### ISSUE TITLE
Simply including your js file creates exception for jquery.

### ISSUE THREAD

**Issue by MACscr** [hosuaby/Leaflet.SmoothMarkerBouncing#22]
I only have the js file linked to in the html with without adding any other js to the page to use it and it creates the following exception:

![image](https://user-images.githubusercontent.com/1404944/61097178-d837fc80-a41f-11e9-9f02-a8148112a172.png)

Im using leaflet 1.5.1 and jquery 3.4.1

**Comment by hosuaby** [comment]
The last time this library was updated, it was on Leaflet 1.3.1. I am not sure it still compatible

**Comment by hosuaby** [comment]
v2.0.0 is garanted to be compatible with Leaflet 1.7.x. 

But I think, the problem here, is that plugin was not imported right. The right way:
```js
import L from 'leaflet';
import 'leaflet.smooth_marker_bouncing/dist/bundle';
```
