### ISSUE TITLE
It is not possible to change the size of the icon when bouncing 

### ISSUE THREAD

**Issue by ironbone** [hosuaby/Leaflet.SmoothMarkerBouncing#26]
For a bouncing marker with an icon, there is no effect when setting a new icon (in my case I wanted to resize the icon when zooming).
It also does not work after calling 
.stopBouncing();

**Comment by hosuaby** [comment]
Yes. Plugin do not recalculate animation when you set a new icon to marker. It's not very common situation.
As alternative, you can just replace one marker by another (with different icon).
If you find an elegant solution to handle icon change in plugin, don't hesitate to make a PR.

**Comment by hosuaby** [comment]
It is possible to change icon of bouncing marker starting from version `3.0.1`.
