### ISSUE TITLE
Find point

### ISSUE THREAD

**Issue by lvcsistemas** [hosuaby/Leaflet.SmoothMarkerBouncing#27]
I liked so much your plugin.

I have a list with all the points in the map and I would like to click in this list and make the icon bounce, not clicking directly on it.

On Google maps I do something like:

marker[index].setAnimation(google.maps.Animation.BOUNCE);

Thanks in advanced.

**Comment by hosuaby** [comment]
Thanks, @lvcsistemas . It's always a pleasure to hear that :)

You don't necessairy need to click on the marker to start bouncing animation. You can make like in your example for google.maps bouncing. Assuming, you have references to all markers in the list you can do just:

```javascript
marker[index].bounce();
```
Keep one thing in mind! You need to add marker to the map before the call to `.bounce()` method:

```javascript
marker[index].addTo(map)
```

**Comment by lvcsistemas** [comment]
Simply perfect, I did as you mentioned and now is working as I want.

Thanks a lot.
