### ISSUE TITLE
not working with leaflet-rotatedmarker

### ISSUE THREAD

**Issue by Mellowz** [hosuaby/Leaflet.SmoothMarkerBouncing#28]
after import "leaflet.smooth_marker_bouncing" then "setRotationAngle" function of leaflet-rotatedmarker is undefined

**Comment by hosuaby** [comment]
Hello, @Mellowz 
I checked out 'leaflet-rotatedmarker' . It's curious. How do you expect it to bounce when marker is rotated?

Shoud it make only vertical movement or move in deirection of rotation ?

**Comment by Mellowz** [comment]
I didn't expect to use rotate marker with bounce, but when import Leaflet.SmoothMarkerBouncing it seem function setRatation is undefined

the rotate marker is about vehicle direction,
but i want to use bounce for pin place.

**Comment by hosuaby** [comment]
I just tested it together with `leaflet-rotatedmarker`. It's works perfectly. Maybe the problem is the way it import it ?
