### ISSUE TITLE
not correctly work with Leaflet.markercluster

### ISSUE THREAD

**Issue by Olegga666** [hosuaby/Leaflet.SmoothMarkerBouncing#3]
good plugin but unfortunately not correctly work with https://github.com/Leaflet/Leaflet.markercluster.
I click on marker - marker bouncing, i zoom out map - marker clustering, when zoom in - bouncing marker stop bouncing, and when i click another marker, he hide.

**Comment by hosuaby** [comment]
Looks like trhe issue #1 . What version of plugin do you use ? This behaiviour was fixed in v1.1.4

**Comment by Olegga666** [comment]
you're right, it works, I used the wrong version. Many thanks
