### ISSUE TITLE
Compatibility with React-Leaflet

### ISSUE THREAD

**Issue by cormac-doyle** [hosuaby/Leaflet.SmoothMarkerBouncing#42]
Is this compatible with react-leaflet

**Comment by hosuaby** [comment]
I never tested this plugin with React-Leaflet, but as longer as global Leaflet variable **L** is available, it must be fine.

**Comment by JLMadsen** [comment]
It is, but you need to access map from a child component in \<MapContainer>.

Such as a custom made \<MapController>

```jsx
// ref for controller
const mapController = useRef();

// render
<MapContainer>
    {other stuff...}
    <MapController ref={mapController }/>
<MapController/>

// use
mapController.current.bounceMarker(latLng)

```

You can access mapController with a forwardRef.

```js
const MapController = forwardRef((props, ref) => {
    const map = useMap();

    const bounceMarker = (latLng) => {
        map.eachLayer(async (layer) => {
            if (layer instanceof L.Marker) {
                if (layer.getLatLng() == latLng ) {
                    layer.bounce();
                } else {
                    layer.stopBouncing();
                }
            }
        });
    }

    useImperativeHandle(ref, () => ({
        bounceMarker(latLng) {
            bounceMarker(latLng);
        },
    }));
};
```

This example iterates through the map layers and just compares position, you can do it with other properties too.

**Comment by hldh214** [comment]
> It is, but you need to access map from a child component in <MapContainer>.
> 
> Such as a custom made <MapController>
> 
> ```js
> // ref for controller
> const mapController = useRef();
> 
> // render
> <MapContainer>
>     {other stuff...}
>     <MapController ref={mapController }/>
> <MapController/>
> 
> // use
> mapController.current.bounceMarker(latLng)
> ```
> 
> You can access mapController with a forwardRef.
> 
> ```js
> const MapController = forwardRef((props, ref) => {
>     const map = useMap();
> 
>     const bounceMarker = (latLng) => {
>         map.eachLayer((layer) => {
>             if (layer instanceof L.Marker) {
>                 if (layer.getLatLng() == latLng ) {
>                     layer.bounce();
>                 } else {
>                     layer.stopBouncing();
>                 }
>             }
>         });
>     }
> 
>     useImperativeHandle(ref, () => ({
>         bounceMarker(latLng) {
>             bounceMarker(latLng);
>         },
>     }));
> };
> ```
> 
> This example iterates through the map layers and just compares position, you can do it with other properties too.

Hi Jakob,

Thank you for sharing. I read your blog on Medium regarding this topic and incorporated it into my project. It has been very helpful.

However, I encountered an issue while attempting to add a bounce effect. I received the error message `layer.bounce is not a function`. I initially thought that I might be missing an import, but I am unsure of which one and where to include it. Could you please provide some guidance? Thank you.
