### ISSUE TITLE
3.0 behaves differently

### ISSUE THREAD

**Issue by bpolaszek** [hosuaby/Leaflet.SmoothMarkerBouncing#44]
Hello there! 👋 

Are we supposed to expect a different bouncing behavior with 3.0.0? 

I created a playground where:
- Bouncing options are different than defaults
- Bouncing options change every 3s

It works well with 2.0.1, and it's completely broken in 3.0.0 (tested on Chrome 102, Firefox 101, MacOS)
- [2.0.1 version](https://jsfiddle.net/xypjt4qn/29/)
- [3.0.0 version](https://jsfiddle.net/xypjt4qn/30/) (same as above except _Leaflet.SmoothMarkerBouncing_ version)

Thanks,
Ben

**Comment by hosuaby** [comment]
Hello @bpolaszek !

Thank you for reporting issue. Starting from 3.0.0 plugin uses CSS3 keyframes (instead of javascript like in 2.0.x) to make animation. I will check carefully your examples and will see how we can fix the differences in behavior.

**Comment by bpolaszek** [comment]
Hi @hosuaby, thanks for your quick answer.
Apart from the animation, it looks like `marker.setBouncingOptions()` can only be called once - further calls just appear to be dismissed or at least have no effect on the animation.

**Comment by hosuaby** [comment]
@bpolaszek fix is made and will be available in `3.0.1`.
