### ISSUE TITLE
Problem with marker animation on mouseenter, mouseleave events on the required element.

### ISSUE THREAD

**Issue by snegokmf** [hosuaby/Leaflet.SmoothMarkerBouncing#45]
Greetings Alexey!
Thank you for your citizenship and the message "Stop the war". For me, as a resident of Ukraine, this is very important and every day people die from bombs, rocket attacks, bullets from russian occupiers ... It is necessary by any means to stop the war and the main, fucking terrorist of the planet, хуйла (putin).

Also thanks for the great plugin. Only, there was a problem with marker animation on mouseenter, mouseleave events on the required element. This is clearly seen in the awesome.html example. Attached is a link to a video showing the problem.
https://drive.google.com/file/d/1MUDV9R2ZpiL-Z1x_Oxx7_umJF9apFyjS/view?usp=sharing

Also, I want to draw your attention to the fact that starting from version 3, the bounceend event does not work.

**Comment by hosuaby** [comment]
Hello, @snegokmf 

Thanks for reporting those bugs. I just fixed both of them and publishhed a new release `3.0.2`.

Best
Alexey

**Comment by snegokmf** [comment]
Great job. Thank you, Alexey!
