### ISSUE TITLE
Start bouncing synchronously

### ISSUE THREAD

**Issue by pvodoz** [hosuaby/Leaflet.SmoothMarkerBouncing#50]
Hi,
When applying the bounce method to a list of markers through a foreach loop, the boucing of all markers is not synchronous when the number of markers is quite important.
Is there any way to synchronize bouncing for all bouncing markers?
Thanks

**Comment by hosuaby** [comment]
Hello, @pvodoz 

This is true. There is no way to synchronize bouncing of markers. Even if they all start at the same time, they quickly become desynchronized when map is moved or resized.

**Comment by hosuaby** [comment]
Closed cause cannot be solved.
