### ISSUE TITLE
Instant stop

### ISSUE THREAD

**Issue by timothyarmes** [hosuaby/Leaflet.SmoothMarkerBouncing#52]
It would be really useful to have a way to instantly stop bouncing, rather than wait till the end of the current animation

**Comment by hosuaby** [comment]
Hello @timothyarmes 

Thanks for enhancement proposal. I think, the proper solution would be to add flag `immediate` in the arguments of method `marker.stopBouncing()` and introduce option `stopImmediately` into options of bouncing.

I find your proposal interesting. I will take care of it when I will have some free time. If you need it fast, feel free to make a PR and I will review.

**Comment by hosuaby** [comment]
Will be availbale in version `3.1.0`
