### ISSUE TITLE
Compatibility with Leaflet 1.x

### ISSUE THREAD

**Issue by jvolker** [hosuaby/Leaflet.SmoothMarkerBouncing#7]
I'm getting this error using Leaflet 1.0.3:
`leaflet.smoothmarkerbouncing.js:841 Uncaught TypeError: Cannot read property 'options' of undefined`

Whereas the current demo is using Leaflet 0.7.3. So I'm wondering if the plugin is compatible to Leaflet 1.x?

**Comment by hosuaby** [comment]
Plugin was never tested with Leaflet 1.x. I will check on my side if it is easy to make it compatible.
If you have suggestions, you are free to make a pull-request.

**Comment by hosuaby** [comment]
Plugin was successfully tested with Leaflet 1.x. Recommended version to use is v1.2.0
